// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3k76RO4Y7xPXJ69NArlusjwKjUqBXFw',
    appId: '1:336085585622:web:0d8c4a5f0840c8494b8377',
    messagingSenderId: '336085585622',
    projectId: 'fir-9d0b8',
    authDomain: 'fir-9d0b8.firebaseapp.com',
    storageBucket: 'fir-9d0b8.firebasestorage.app',
    measurementId: 'G-2T567GW7CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuckBiPG4QFtwYjAF2iAU7zuh-9Tw-9k',
    appId: '1:336085585622:android:1be8b5c2ffce44114b8377',
    messagingSenderId: '336085585622',
    projectId: 'fir-9d0b8',
    storageBucket: 'fir-9d0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDYgq6bZSYzpMnqLdjy14I5MydC7dclUE',
    appId: '1:336085585622:ios:6c50cb2e79a429824b8377',
    messagingSenderId: '336085585622',
    projectId: 'fir-9d0b8',
    storageBucket: 'fir-9d0b8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDYgq6bZSYzpMnqLdjy14I5MydC7dclUE',
    appId: '1:336085585622:ios:6c50cb2e79a429824b8377',
    messagingSenderId: '336085585622',
    projectId: 'fir-9d0b8',
    storageBucket: 'fir-9d0b8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3k76RO4Y7xPXJ69NArlusjwKjUqBXFw',
    appId: '1:336085585622:web:ec8e667586fc7e294b8377',
    messagingSenderId: '336085585622',
    projectId: 'fir-9d0b8',
    authDomain: 'fir-9d0b8.firebaseapp.com',
    storageBucket: 'fir-9d0b8.firebasestorage.app',
    measurementId: 'G-S2D6D24ZEX',
  );
}
